name: "CI/CD"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          node-version: "18.x"

      - name: "Install NPM packages"
        run: "yarn"

      - name: "Build"
        run: "yarn build"

      - name: "Run tests"
        run: "yarn test --passWithNoTests"

      - name: "Upload build artifacts"
        uses: "actions/upload-artifact@v3"
        with:
          name: "build-artifacts"
          path: "./build"

  deploy:
    name: "Deploy"
    needs: "build"
    runs-on: "ubuntu-latest"
    if: "github.ref == 'refs/heads/master'"

    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v3
        with:
          name: "build-artifacts"
          path: "./build"

      - name: Deploy to GitHub Pages
        uses: "peaceiris/actions-gh-pages@v3"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./build"
